// ============================================================
// DomainTracker - Sample Data
// Replace this with real API/database calls in production
// ============================================================

import { Domain, DomainActivity, RenewalRecord } from "@/types";
import { addDays, subDays, subMonths, format } from "date-fns";

const now = new Date();

export const sampleDomains: Domain[] = [
  {
    id: "dom_001",
    name: "mycompany.com",
    registrar: "Namecheap",
    purchaseDate: format(subMonths(now, 24), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 280), "yyyy-MM-dd"),
    renewalCost: 12.99,
    autoRenew: true,
    notes: "Primary company domain. Keep auto-renew on at all times.",
    tags: ["primary", "business"],
    status: "safe",
    createdAt: subMonths(now, 24).toISOString(),
    updatedAt: subMonths(now, 1).toISOString(),
  },
  {
    id: "dom_002",
    name: "mycompany.io",
    registrar: "Cloudflare",
    purchaseDate: format(subMonths(now, 18), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 22), "yyyy-MM-dd"),
    renewalCost: 28.0,
    autoRenew: false,
    notes: "Tech-focused brand domain. Used for developer portal.",
    tags: ["brand", "tech"],
    status: "expiring-soon",
    createdAt: subMonths(now, 18).toISOString(),
    updatedAt: subDays(now, 5).toISOString(),
  },
  {
    id: "dom_003",
    name: "mycompany.net",
    registrar: "GoDaddy",
    purchaseDate: format(subMonths(now, 36), "yyyy-MM-dd"),
    expiryDate: format(subDays(now, 5), "yyyy-MM-dd"),
    renewalCost: 14.99,
    autoRenew: false,
    notes: "Redirect to main domain. Consider letting it expire.",
    tags: ["redirect"],
    status: "expired",
    createdAt: subMonths(now, 36).toISOString(),
    updatedAt: subDays(now, 6).toISOString(),
  },
  {
    id: "dom_004",
    name: "shop.mycompany.com",
    registrar: "Namecheap",
    purchaseDate: format(subMonths(now, 12), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 145), "yyyy-MM-dd"),
    renewalCost: 12.99,
    autoRenew: true,
    notes: "E-commerce subdomain for the shop.",
    tags: ["ecommerce", "primary"],
    status: "safe",
    createdAt: subMonths(now, 12).toISOString(),
    updatedAt: subMonths(now, 3).toISOString(),
  },
  {
    id: "dom_005",
    name: "getmyapp.com",
    registrar: "Google Domains",
    purchaseDate: format(subMonths(now, 6), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 55), "yyyy-MM-dd"),
    renewalCost: 12.0,
    autoRenew: false,
    notes: "Marketing landing page for mobile app.",
    tags: ["marketing", "app"],
    status: "expiring-soon",
    createdAt: subMonths(now, 6).toISOString(),
    updatedAt: subDays(now, 15).toISOString(),
  },
  {
    id: "dom_006",
    name: "mycompany.co",
    registrar: "Cloudflare",
    purchaseDate: format(subMonths(now, 8), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 200), "yyyy-MM-dd"),
    renewalCost: 30.0,
    autoRenew: true,
    notes: "Short brand domain. Keep protected.",
    tags: ["brand"],
    status: "safe",
    createdAt: subMonths(now, 8).toISOString(),
    updatedAt: subMonths(now, 2).toISOString(),
  },
  {
    id: "dom_007",
    name: "dev.mycompany.com",
    registrar: "Namecheap",
    purchaseDate: format(subMonths(now, 15), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 320), "yyyy-MM-dd"),
    renewalCost: 12.99,
    autoRenew: true,
    notes: "Developer environment and staging.",
    tags: ["development", "internal"],
    status: "safe",
    createdAt: subMonths(now, 15).toISOString(),
    updatedAt: subMonths(now, 4).toISOString(),
  },
  {
    id: "dom_008",
    name: "blog.mycompany.com",
    registrar: "Namecheap",
    purchaseDate: format(subMonths(now, 20), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 75), "yyyy-MM-dd"),
    renewalCost: 12.99,
    autoRenew: false,
    notes: "Company blog. May migrate to subdirectory.",
    tags: ["marketing", "content"],
    status: "expiring-soon",
    createdAt: subMonths(now, 20).toISOString(),
    updatedAt: subDays(now, 2).toISOString(),
  },
  {
    id: "dom_009",
    name: "mycompany.org",
    registrar: "Google Domains",
    purchaseDate: format(subMonths(now, 30), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 400), "yyyy-MM-dd"),
    renewalCost: 12.0,
    autoRenew: true,
    notes: "Defensive registration.",
    tags: ["defensive"],
    status: "renewed",
    createdAt: subMonths(now, 30).toISOString(),
    updatedAt: subDays(now, 10).toISOString(),
  },
  {
    id: "dom_010",
    name: "helpmycompany.com",
    registrar: "GoDaddy",
    purchaseDate: format(subMonths(now, 4), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 240), "yyyy-MM-dd"),
    renewalCost: 17.99,
    autoRenew: true,
    notes: "Customer support portal domain.",
    tags: ["support", "business"],
    status: "safe",
    createdAt: subMonths(now, 4).toISOString(),
    updatedAt: subMonths(now, 1).toISOString(),
  },
  {
    id: "dom_011",
    name: "mycompany.app",
    registrar: "Cloudflare",
    purchaseDate: format(subMonths(now, 10), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 10), "yyyy-MM-dd"),
    renewalCost: 18.0,
    autoRenew: false,
    notes: "App-focused TLD. Renewal pending decision.",
    tags: ["app", "brand"],
    status: "expiring-soon",
    createdAt: subMonths(now, 10).toISOString(),
    updatedAt: subDays(now, 1).toISOString(),
  },
  {
    id: "dom_012",
    name: "mycompany.dev",
    registrar: "Cloudflare",
    purchaseDate: format(subMonths(now, 14), "yyyy-MM-dd"),
    expiryDate: format(addDays(now, 180), "yyyy-MM-dd"),
    renewalCost: 12.0,
    autoRenew: true,
    notes: "Dev environment branding.",
    tags: ["development"],
    status: "safe",
    createdAt: subMonths(now, 14).toISOString(),
    updatedAt: subMonths(now, 2).toISOString(),
  },
];

export const sampleActivity: DomainActivity[] = [
  {
    id: "act_001",
    domainId: "dom_011",
    domainName: "mycompany.app",
    type: "expiry-warning",
    message: "mycompany.app expires in 10 days — action required.",
    timestamp: subDays(now, 1).toISOString(),
  },
  {
    id: "act_002",
    domainId: "dom_009",
    domainName: "mycompany.org",
    type: "renewed",
    message: "mycompany.org was successfully renewed for 1 year.",
    timestamp: subDays(now, 10).toISOString(),
  },
  {
    id: "act_003",
    domainId: "dom_003",
    domainName: "mycompany.net",
    type: "expiry-warning",
    message: "mycompany.net has expired — renew immediately or let it go.",
    timestamp: subDays(now, 5).toISOString(),
  },
  {
    id: "act_004",
    domainId: "dom_010",
    domainName: "helpmycompany.com",
    type: "added",
    message: "helpmycompany.com was added to the tracker.",
    timestamp: subMonths(now, 4).toISOString(),
  },
  {
    id: "act_005",
    domainId: "dom_002",
    domainName: "mycompany.io",
    type: "expiry-warning",
    message: "mycompany.io expires in 22 days — renewal needed soon.",
    timestamp: subDays(now, 3).toISOString(),
  },
  {
    id: "act_006",
    domainId: "dom_006",
    domainName: "mycompany.co",
    type: "edited",
    message: "mycompany.co details were updated.",
    timestamp: subMonths(now, 2).toISOString(),
  },
];

export const sampleRenewalHistory: RenewalRecord[] = [
  {
    id: "ren_001",
    domainId: "dom_001",
    renewedAt: subMonths(now, 12).toISOString(),
    newExpiryDate: format(addDays(now, 280), "yyyy-MM-dd"),
    cost: 12.99,
    notes: "Annual auto-renewal via Namecheap.",
  },
  {
    id: "ren_002",
    domainId: "dom_009",
    renewedAt: subDays(now, 10).toISOString(),
    newExpiryDate: format(addDays(now, 400), "yyyy-MM-dd"),
    cost: 12.0,
    notes: "Manually renewed via Google Domains.",
  },
];
